version: '3'
services:
  mobsf:
    build: ./mobsf
    ports:
      - "8001:8000"
    environment:
      - MOBSF_API_KEY=this-is-my-key
    networks:
      - android_security_net

  backend:
    build: .
    ports:
      - "8000:80"
    environment:
      - MOBSF_SECRET=this-is-my-key
      - MOBSF_URL=http://mobsf:8000
      - QIANFAN_AK=${QIANFAN_AK}
      - QIANFAN_SK=${QIANFAN_SK}
      - SQLITE_URL=sqlite:///database.db
    networks:
      - android_security_net

networks:
  android_security_net:
    driver: bridge
